config/routes.rb
Myapp::Application.routes.draw do

  devise_for :users
  resources :users

  resources :events
  resources :posts
  resources :images
  resources :uploads

  get '/about', to: 'welcome#about', as: 'about'

  root to: "welcome#index"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sandbox42 - Exploring Ruby on Rails
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    - yield :head
  %body

    %nav{class: 'navbar navbar-default', role: "navigation"}
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Sandbox42', root_path, class: 'navbar-brand'
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to "Posts", posts_path
            %li= link_to "Events", events_path
            %li= link_to "Uploads", uploads_path
            %li= link_to "Images", images_path
            %li
              %a{:href => "#"} Link
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Dropdown
                %b.caret
              %ul.dropdown-menu
                %li
                  %a{:href => "#"} Action
                %li
                  %a{:href => "#"} Another action
                %li
                  %a{:href => "#"} Something else here
                %li.divider
                %li
                  %a{:href => "#"} Separated link
                %li.divider
                %li
                  %a{:href => "#"} One more separated link
          %form.navbar-form.navbar-left{:role => "search"}
            .form-group
              %input.form-control{:placeholder => "Search", :type => "text"}/
            %button.btn.btn-default{:type => "submit"} Submit
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "About", about_path
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Dropdown
                %b.caret
              %ul.dropdown-menu
                %li
                  %a{:href => "#"} Action
                %li
                  %a{:href => "#"} Another action
                %li
                  %a{:href => "#"} Something else here
                %li.divider
                %li
                  %a{:href => "#"} Separated link
      / /.navbar-collapse
      / /.container-fluid
    %p.notice= notice
    %p.alert= alert

    .main-page-content
      = yield